"""first migrate

Revision ID: 0607d1c76451
Revises: 
Create Date: 2024-12-28 22:10:29.657132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0607d1c76451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('given_name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('streetaddress', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=70), nullable=False),
    sa.Column('zipcode', sa.String(length=15), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=False),
    sa.Column('telephone_country_code', sa.String(length=10), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=False),
    sa.Column('email_address', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Enum('PERSONAL', 'CHECKING', 'SAVINGS', name='accounttype', create_constraint=True), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['Customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DEBIT', 'CREDIT', name='transactiontype', create_constraint=True), nullable=False),
    sa.Column('operation', sa.Enum('SALARY', 'TRANSFER', 'DEPOSIT_CASH', 'ATM_WITHDRAWL', 'PAYMENT', 'BANK_WITHDRAWL', name='transactionoperation', create_constraint=True), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('new_balance', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['Accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transactions')
    op.drop_table('Accounts')
    op.drop_table('Customers')
    # ### end Alembic commands ###
