"""Added permissions field to Role

Revision ID: a3c2818b2561
Revises: 65be059173a7
Create Date: 2025-02-27 21:08:18.812246

"""
import flask_security
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c2818b2561'
down_revision = '65be059173a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs_webauthn_user_handle', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('mf_recovery_codes', flask_security.datastore.AsaList(), nullable=True))
        batch_op.add_column(sa.Column('us_phone_number', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('us_totp_secrets', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('current_login_ip', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tf_primary_method', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('tf_totp_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tf_phone_number', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.create_unique_constraint(None, ['us_phone_number'])
        batch_op.create_unique_constraint(None, ['fs_webauthn_user_handle'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('update_datetime')
        batch_op.drop_column('create_datetime')
        batch_op.drop_column('tf_phone_number')
        batch_op.drop_column('tf_totp_secret')
        batch_op.drop_column('tf_primary_method')
        batch_op.drop_column('login_count')
        batch_op.drop_column('current_login_ip')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('current_login_at')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('us_totp_secrets')
        batch_op.drop_column('us_phone_number')
        batch_op.drop_column('mf_recovery_codes')
        batch_op.drop_column('fs_webauthn_user_handle')

    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.drop_column('update_datetime')
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###
